### ISSUE TITLE
请问这个文件也是trtexec转化过来的吗？我尝试运行infer_backend_mix.py文件，显示了这个报错。

### ISSUE THREAD

**Issue by DoiiarX** [foocker/Bert-VITS2-Faster#6]
(bertvitsextra2Chinese) PS D:\Doiiars> python infer_backend_mix.py
Traceback (most recent call last):
  File "Doiiars\infer_backend_mix.py", line 355, in <module>
    TRTI = TRTModelInfer(engine_path)
  File "D:\Doiiars\infer_backend_mix.py", line 46, in __init__
    with open(engine_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './engines/chinese_roberta_wwm_ext_large_model_fp16_dynamic.engine'

我尝试运行infer_backend_mix.py文件，显示了这个报错。

**Comment by DoiiarX** [comment]
已解决。是。
